# Deployment Security Policy
# This policy defines security requirements for deployments, focusing on canary releases
# and ensuring secure deployment practices

version: "1.0"
name: "Secure Deployment Policy"
description: "Security policy for application deployments, with focus on canary releases"

# Deployment security gates that must pass before promotion
deployment_gates:
  pre_deployment:
    # Security checks that must pass before any deployment
    enabled: true
    required_gates:
      # Vulnerability scanning thresholds
      vulnerability_scan:
        enabled: true
        max_severity_allowed:
          critical: 0
          high: 0
          medium: 5
          low: 10
        exceptions:
          - id: "CVE-2023-XXXXX"
            reason: "False positive, confirmed with vendor"
            expires: "2023-12-31"
      
      # Static application security testing requirements
      sast_scan:
        enabled: true
        max_severity_allowed:
          critical: 0
          high: 0
          medium: 3
          low: 10
      
      # License compliance requirements
      license_compliance:
        enabled: true
        blacklisted_licenses:
          - "GPL-3.0"
          - "AGPL-3.0"
        whitelisted_licenses:
          - "MIT"
          - "Apache-2.0"
          - "BSD-3-Clause"
      
      # Dependency verification requirements
      dependency_verification:
        enabled: true
        require_signed_dependencies: true
        allowed_dependency_sources:
          - "internal-registry.example.com"
          - "registry.npmjs.org"
          - "pypi.org"
        blocked_dependencies: []
      
      # Secret scanning to prevent leakage
      secret_scan:
        enabled: true
        action: "fail"  # fail, warn, or ignore
      
      # Code quality gates
      code_quality:
        enabled: true
        minimum_test_coverage: 75
        maximum_complexity: 25

  canary_deployment:
    # Security checks specific to canary deployments
    enabled: true
    required_gates:
      # Network security requirements
      network_security:
        enabled: true
        required_network_policies: true
        allowed_egress_only: true
        restricted_ingress: true
      
      # Runtime security requirements
      runtime_security:
        enabled: true
        privileged_containers: false
        root_containers: false
        read_only_filesystem: true
        drop_capabilities: ["ALL"]
        retain_capabilities: ["NET_BIND_SERVICE"]
      
      # Resource limits to prevent DoS
      resource_limits:
        enabled: true
        require_limits: true
        require_requests: true
        memory_limit_required: true
        cpu_limit_required: true
      
      # Security context requirements
      security_context:
        enabled: true
        run_as_non_root: true
        run_as_user_ranges:
          min: 1000
          max: 65535
        read_only_root_filesystem: true
      
      # Secure service configuration
      service_security:
        enabled: true
        enforce_https: true
        enforce_mutual_tls: false
        min_tls_version: "1.2"
        http_security_headers: true

  canary_monitoring:
    # Security monitoring thresholds during canary phase
    enabled: true
    required_monitoring:
      # Traffic pattern anomaly detection
      traffic_monitoring:
        enabled: true
        alert_on_traffic_spikes: true
        alert_on_error_rate_increase: true
        error_rate_threshold: 5.0  # percentage
        latency_increase_threshold: 200  # percentage
      
      # Runtime vulnerability monitoring
      vulnerability_monitoring:
        enabled: true
        runtime_scanning_required: true
        alert_on_new_vulnerabilities: true
      
      # Network activity monitoring
      network_monitoring:
        enabled: true
        alert_on_unexpected_connections: true
        alert_on_unexpected_ports: true
        alert_on_unexpected_protocols: true
      
      # Resource usage monitoring to detect potential compromise
      resource_monitoring:
        enabled: true
        cpu_usage_threshold: 300  # percentage above baseline
        memory_usage_threshold: 200  # percentage above baseline
        alert_on_unusual_processes: true
      
      # Security log monitoring
      log_monitoring:
        enabled: true
        alert_on_security_events: true
        required_log_sources:
          - "application"
          - "network"
          - "system"
          - "api-access"
      
      # Authentication/authorization monitoring
      auth_monitoring:
        enabled: true
        alert_on_privilege_escalation: true
        alert_on_unusual_access_patterns: true

  promotion_criteria:
    # Criteria for promoting a canary to full deployment
    enabled: true
    required_criteria:
      # Security-specific promotion criteria
      security:
        no_critical_security_events: true
        no_high_security_events: true
        max_medium_security_events: 3
        no_unusual_network_activity: true
        no_unexpected_system_changes: true
        no_privilege_escalation_attempts: true
      
      # Performance-related security criteria
      performance:
        no_significant_performance_degradation: true
        no_resource_exhaustion_events: true
        no_unusual_resource_consumption: true
      
      # Minimum canary evaluation period
      timing:
        minimum_monitoring_minutes: 30
        minimum_traffic_volume: 1000  # requests

# Configuration for rollback triggers
rollback_triggers:
  security:
    - trigger: "critical_vulnerability_detected"
      description: "Critical vulnerability detected in runtime"
      automatic: true
    
    - trigger: "sensitive_data_exposure"
      description: "Sensitive data exposure detected"
      automatic: true
    
    - trigger: "suspicious_network_activity"
      description: "Suspicious network activity detected"
      automatic: true
    
    - trigger: "privilege_escalation"
      description: "Privilege escalation attempt detected"
      automatic: true
    
    - trigger: "abnormal_resource_usage"
      description: "Abnormal resource usage detected"
      automatic: false  # Requires manual review
    
    - trigger: "unexpected_system_change"
      description: "Unexpected system change detected"
      automatic: true

# Post-deployment security monitoring configuration
post_deployment_monitoring:
  enabled: true
  duration_hours: 48
  enhanced_security_logging: true
  increased_sampling_rate: true
  alert_thresholds:
    lowered: true
    sensitivity: "high"
  
  required_validations:
    secure_headers_check: true
    authentication_validation: true
    authorization_validation: true
    input_validation_check: true
    output_encoding_check: true
    secure_session_validation: true

# Security notifications configuration
security_notifications:
  channels:
    - type: "slack"
      name: "#security-alerts"
      events:
        - "deployment_started"
        - "deployment_completed"
        - "security_event_detected"
        - "rollback_triggered"
    
    - type: "email"
      name: "security-team@example.com"
      events:
        - "security_event_detected"
        - "rollback_triggered"
    
    - type: "webhook"
      name: "https://security.example.com/deployment-events"
      events:
        - "deployment_started"
        - "deployment_completed"
        - "security_event_detected"
        - "rollback_triggered"

# Audit logging requirements
audit_logging:
  enabled: true
  retention_days: 90
  protected: true
  required_events:
    - "deployment_initiated"
    - "canary_created"
    - "traffic_shifted"
    - "monitoring_started"
    - "security_event_detected"
    - "rollback_triggered"
    - "deployment_promoted"
    - "deployment_completed"